### ISSUE TITLE
Still problems after restart of HASS after upgrade to 0.4.7

### ISSUE THREAD

**Issue by briis** [MTrab/energidataservice#147]
### Environment:
- Home Assistant version: 2022.12.4
- Energidatastyrelsen version: 0.4.7
- Operation system: Supervised

## Configuration
- Country: Denmark
- Region: East of the great belt
- Show in cents: No
- Number of decimals: 3

## Additional cost template

```yaml
        {% set s = 
          { "abonnement_net": 0.00,
            "abonnement_ellev": 0.00,
            "transmissions_nettarif": 0.049,
            "systemtarif": 0.061,
            "balancetarif": 0.00229,
            "spot_tillaeg": 0.0,
            "elafgift_2022": 0.763,
            "elafgift_2023": 0.064,
            "nettarif_lavlast_2022": 0.3003,
            "nettarif_spidslast_2022": 0.7651,
            "nettarif_2023_vinter_lav": 0.17008,
            "nettarif_2023_vinter_hoej": 0.51032,
            "nettarif_2023_vinter_spids": 1.53080,
            "nettarif_2023_sommer_lav": 0.17008,
            "nettarif_2023_sommer_hoej": 0.25512,
            "nettarif_2023_sommer_spids": 0.66328 } 
        %} 

        {% set cdt = now() %}
        {% if cdt.year == 2022 %} 
          {% set fast_sum = s.abonnement_net + s.abonnement_ellev + s.spot_tillaeg + s.elafgift_2022 + s.transmissions_nettarif + s.systemtarif + s.balancetarif %}
          {% if cdt.month >= 10 or cdt.month < 4 %} 
            {% if cdt.hour >= 17 and cdt.hour < 21%} 
              {{s.nettarif_spidslast_2022 + fast_sum}} 
            {% else %} {{s.nettarif_lavlast_2022 + fast_sum}} 
            {% endif %}
          {% else %}
            {{s.nettarif_lavlast_2022 + fast_sum}}
          {% endif %}
        {% else %}
          {% set fast_sum = s.abonnement_net + s.abonnement_ellev + s.spot_tillaeg + s.elafgift_2023 + s.transmissions_nettarif + s.systemtarif + s.balancetarif %}
          {% if cdt.month >= 10 or cdt.month < 4 %} 
            {% set nettarif_lav = s.nettarif_2023_vinter_lav %}
            {% set nettarif_hoej = s.nettarif_2023_vinter_hoej %}
            {% set nettarif_spids = s.nettarif_2023_vinter_spids %}
          {% else %}
            {% set nettarif_lav = s.nettarif_2023_sommer_lav %}
            {% set nettarif_hoej = s.nettarif_2023_sommer_hoej %}
            {% set nettarif_spids = s.nettarif_2023_sommer_spids %}
          {% endif %}
          {% if cdt.hour >= 17 and cdt.hour < 21 %} 
            {{nettarif_spids + fast_sum}} 
          {% else %}
            {% if cdt.hour >= 0 and cdt.hour < 6 %}
              {{nettarif_lav + fast_sum}}
            {% else %}
              {{nettarif_hoej + fast_sum}}
            {% endif %}
          {% endif %}
        {% endif %}


```

## Describe the bug
I had the samme reload issues as many others reported on FB and now I just upgraded to 0.4.7 and still get errors when doing that. Debug log is below

## Debug log

```text
Logger: homeassistant.components.sensor
Source: custom_components/energidataservice/sensor.py:535
Integration: Sensor (documentation, issues)
First occurred: 15.44.22 (2 occurrences)
Last logged: 15.44.22

Error adding entities for domain sensor with platform energidataservice
Error while setting up energidataservice platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 692, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 788, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/energidataservice/sensor.py", line 385, in async_added_to_hass
    await self.validate_data()
  File "/config/custom_components/energidataservice/sensor.py", line 250, in validate_data
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/energidataservice/sensor.py", line 566, in _format_list
    price = self._calculate(
  File "/config/custom_components/energidataservice/sensor.py", line 535, in _calculate
    template_value + (value / UNIT_TO_MULTIPLIER[self._price_type])
TypeError: can only concatenate str (not "float") to str

```

## Diganostics data from the device

```text

Add your diagnostics here.

```

**Comment by MTrab** [comment]
And your diagnostics? Not sure this is the same error, as nobody have reported any errors from the logs before - and this section of the code haven't been touched for some time.

**Comment by briis** [comment]
I found the error (I think). I have the value of the additional cost done in a template sensor, and then I just put `{{ states("sensor.additional_cost") }}` in the additional field on your integration. But I suspect that your integration is loaded before the template sensors, and as such it will throw the error above. Putting in the yaml code directly seems to have solved the issue
