### ISSUE TITLE
Weird prices

### ISSUE THREAD

**Issue by donnib** [MTrab/energidataservice#17]
Hi Morten,
Today (right now) i see weird prices, see the status of the sensor :

```
Current price
190.8
Unit
kWh
Currency
DKK
Area
East of the great belt
Area code
DK2
Tomorrow valid
false
Next data update
13:09:50
Today
200.66, 204.29, 195.02, 181.93, 186.3, 200.69, 246.37, 294, 323.56, 261.75, 226.93, 219.09, 203.92, 193.43, 190.8, 185.62, 184.96, 188.01, 200.01, 229.49, 199.08, 164.35, 150.64, 120.08
Tomorrow
—
Raw today
- hour: '2022-03-31T00:00:00+02:00'
price: 200.66
- hour: '2022-03-31T01:00:00+02:00'
price: 204.29
- hour: '2022-03-31T02:00:00+02:00'
price: 195.02
- hour: '2022-03-31T03:00:00+02:00'
price: 181.93
- hour: '2022-03-31T04:00:00+02:00'
price: 186.3
- hour: '2022-03-31T05:00:00+02:00'
price: 200.69
- hour: '2022-03-31T06:00:00+02:00'
price: 246.37
- hour: '2022-03-31T07:00:00+02:00'
price: 294
- hour: '2022-03-31T08:00:00+02:00'
price: 323.56
- hour: '2022-03-31T09:00:00+02:00'
price: 261.75
- hour: '2022-03-31T10:00:00+02:00'
price: 226.93
- hour: '2022-03-31T11:00:00+02:00'
price: 219.09
- hour: '2022-03-31T12:00:00+02:00'
price: 203.92
- hour: '2022-03-31T13:00:00+02:00'
price: 193.43
- hour: '2022-03-31T14:00:00+02:00'
price: 190.8
- hour: '2022-03-31T15:00:00+02:00'
price: 185.62
- hour: '2022-03-31T16:00:00+02:00'
price: 184.96
- hour: '2022-03-31T17:00:00+02:00'
price: 188.01
- hour: '2022-03-31T18:00:00+02:00'
price: 200.01
- hour: '2022-03-31T19:00:00+02:00'
price: 229.49
- hour: '2022-03-31T20:00:00+02:00'
price: 199.08
- hour: '2022-03-31T21:00:00+02:00'
price: 164.35
- hour: '2022-03-31T22:00:00+02:00'
price: 150.64
- hour: '2022-03-31T23:00:00+02:00'
price: 120.08
Raw tomorrow
- hour: '2022-03-31T00:00:00+02:00'
price: 3.43
- hour: '2022-03-31T01:00:00+02:00'
price: 3.464
- hour: '2022-03-31T02:00:00+02:00'
price: 3.378
- hour: '2022-03-31T03:00:00+02:00'
price: 3.256
- hour: '2022-03-31T04:00:00+02:00'
price: 3.297
- hour: '2022-03-31T05:00:00+02:00'
price: 3.431
- hour: '2022-03-31T06:00:00+02:00'
price: 3.855
- hour: '2022-03-31T07:00:00+02:00'
price: 4.298
- hour: '2022-03-31T08:00:00+02:00'
price: 4.573
- hour: '2022-03-31T09:00:00+02:00'
price: 3.998
- hour: '2022-03-31T10:00:00+02:00'
price: 3.675
- hour: '2022-03-31T11:00:00+02:00'
price: 3.602
- hour: '2022-03-31T12:00:00+02:00'
price: 3.461
- hour: '2022-03-31T13:00:00+02:00'
price: 3.363
- hour: '2022-03-31T14:00:00+02:00'
price: 3.339
- hour: '2022-03-31T15:00:00+02:00'
price: 3.29
- hour: '2022-03-31T16:00:00+02:00'
price: 3.284
- hour: '2022-03-31T17:00:00+02:00'
price: 3.806
- hour: '2022-03-31T18:00:00+02:00'
price: 3.917
- hour: '2022-03-31T19:00:00+02:00'
price: 4.191
- hour: '2022-03-31T20:00:00+02:00'
price: 3.416
- hour: '2022-03-31T21:00:00+02:00'
price: 3.093
- hour: '2022-03-31T22:00:00+02:00'
price: 2.965
- hour: '2022-03-31T23:00:00+02:00'
price: 2.681
Today min
hour: '2022-03-31T23:00:00+02:00'
price: 120.08
Today max
hour: '2022-03-31T08:00:00+02:00'
price: 323.56
Tomorrow min
—
Tomorrow max
—
```
Maybe it's the calculation i have ? I don't know but here it is anyway :

```
{% set s = {
"abonnement": 0.00,
"elafgift": 1.12875,
"systemydelse": 0.14,
"transport_lavlast_2021": 0.2954,
"transport_spidslast_2021": 0.7884,
"transport_lavlast_2022": 0.3754,
"transport_spidslast_2022": 0.9564,
} %}
{% set afgiftsum = s.abonnement + s.elafgift + s.systemydelse %}
{% set cdt = now() %}
{% if cdt<as_datetime("2022-04-01 00:00:00.00+01:00") %}
  {% set transport_lavlast =  s.transport_lavlast_2021 %}
  {% set transport_spidslast =  s.transport_spidslast_2021 %}
{% else %}  
  {% set transport_lavlast =  s.transport_lavlast_2022 %}
  {% set transport_spidslast =  s.transport_spidslast_2022 %}
{% endif %}  
{% if cdt.month >= 10 or cdt.month < 4 %}
  {% if cdt.hour >= 17 and cdt.hour < 20 %}
    {{transport_spidslast + afgiftsum}}
  {% else %}
    {{transport_lavlast + afgiftsum}}
  {% endif %}
{% else %}
  {{transport_lavlast + afgiftsum}}
{% endif %}
```

**Comment by donnib** [comment]
Latest.... 0.1.4

After a restart i see this in the logs :

```
Logger: homeassistant.components.sensor
Source: custom_components/energidataservice/api.py:47
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 14:14:53 (2 occurrences)
Last logged: 14:14:53

Error adding entities for domain sensor with platform energidataservice
Error while setting up energidataservice platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 800, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/energidataservice/sensor.py", line 211, in async_added_to_hass
    await self.validate_data()
  File "/config/custom_components/energidataservice/sensor.py", line 160, in validate_data
    await self._api.update()
  File "/config/custom_components/energidataservice/__init__.py", line 169, in update
    await eds.get_spotprices()
  File "/config/custom_components/energidataservice/api.py", line 47, in get_spotprices
    resp = await self.client.post(url, data=body, headers=headers)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
```
Maybe the service is down ?

**Comment by MTrab** [comment]
Just tried restarting my Home Assistant, no errors in the log relating to this integration and prices looks valid

**Comment by donnib** [comment]
Very strange, i did another reboot then it worked. Intermittent fault :)

**Comment by MTrab** [comment]
Will try to add some handling of such error :)
