### ISSUE TITLE
cannot add instance with fixed price 

### ISSUE THREAD

**Issue by AndersV209** [MTrab/energidataservice#233]
### Environment:

- Home Assistant version: 2023.1.4
- Energidatastyrelsen version: 1.1.1
- Operation system: HAOS

## Additional cost template

```text


```

## Describe the bug
when i try energi data service with a fixed price it just gives an error, it does not matter if i select tariff info or not 

## Debug log

```text
Logger: aiohttp.server
Source: custom_components/energidataservice/config_flow.py:410
Integration: Energi Data Service ([documentation](https://github.com/MTrab/energidataservice/blob/master/README.md), [issues](https://github.com/MTrab/energidataservice/issues))
First occurred: 18.05.33 (17 occurrences)
Last logged: 18.11.24

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 81, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 286, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 374, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/energidataservice/config_flow.py", line 410, in async_step_enable_extras
    if user_input[CONF_ENABLE_FORECAST]:
KeyError: 'enable_forecast'

```

## Diganostics data from the device

cant get this as i cant add it 

```

**Comment by MTrab** [comment]
Thank you for reporting - fixed for next release.
