### ISSUE TITLE
Support for Python 3.11

### ISSUE THREAD

**Issue by centertivevier** [MTrab/energidataservice#278]
Hi,

i get the following error with Python 3.11 on HomeAssistant 2023.03.5

"AttributeError: module 'asyncio' has no attribute 'coroutine'"

[Support for generator-based coroutines is deprecated and is removed in Python 3.11](https://docs.python.org/3.10/library/asyncio-task.html#generator-based-coroutines).

**Comment by MTrab** [comment]
I just configured a test env in Python 3.11 - this error is not directly in the integration rather than in one of the dependencies.

**Comment by centertivevier** [comment]
`Error setting up entry Energi Data Service for energidataservice

Traceback (most recent call last):
  File "/XXX/lib/python3.11/site-packages/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/XDX/.homeassistant/custom_components/energidataservice/__init__.py", line 56, in async_setup_entry
    result = await _setup(hass, entry)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/XXX/.homeassistant/custom_components/energidataservice/__init__.py", line 94, in _setup
    api = APIConnector(hass, entry, rand_min, rand_sec)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/XXX/.homeassistant/custom_components/energidataservice/api.py", line 49, in __init__
    self.tariffs = Tariff()
                   ^^^^^^^^
  File "/XXX/.homeassistant/custom_components/energidataservice/tariffs/__init__.py", line 34, in __init__
    mod = import_module(api_ns, __name__)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/XXX/.homeassistant/custom_components/energidataservice/tariffs/energidataservice/__init__.py", line 10, in <module>
    from async_retrying import retry
  File "/XXX/lib/python3.11/site-packages/async_retrying.py", line 39, in <module>
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'`

This is the complete error message. I'm using Debian Bookworm (Testing) with Homeassistant Core at a LXC Container. On this one is python 3.11 the regular package.

**Comment by MTrab** [comment]
Again - this is a dependency which isn't compatible.
I'll put some pressure on for a change (actually pretty easy) or if that doesn't work, publish a fork myself.
