### ISSUE TITLE
Fetch tariffs from Elinord not working anymore

### ISSUE THREAD

**Issue by Sdahl1234** [MTrab/energidataservice#283]
### Environment:
- Home Assistant version: 2023.3.5
- Energidatastyrelsen version: 1.3.0
- Operation system: HAOS 9.5

## Configuration
- tariff_charge_owner: "Elinord"
- enable_forecast: false
- enable_tariffs: true
- area: "West of the great belt"
- vat: true
- in_cent: false
- decimals: 3
- pricetype: "kWh
- cost_template: "{{0.0|float}}"
- name: "Energi Data Service2"
- country: "Denmark"
## Additional cost template
None

## Describe the bug
Integration fails to load if Elinord is chosen as tariff_charge_owner 

## Debug log

```text

2023-03-20 12:36:25.281 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform energidataservice
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 442, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 717, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 806, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/energidataservice/sensor.py", line 484, in async_added_to_hass
    await self.validate_data()
  File "/config/custom_components/energidataservice/sensor.py", line 289, in validate_data
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/energidataservice/sensor.py", line 727, in _format_list
    price = self._calculate(
  File "/config/custom_components/energidataservice/sensor.py", line 647, in _calculate
    self._api.tariff_data["tariffs"][str(fake_dt.hour)]
KeyError: '0'
2023-03-20 12:36:25.283 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up energidataservice platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 301, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 442, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 717, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 806, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/energidataservice/sensor.py", line 484, in async_added_to_hass
    await self.validate_data()
  File "/config/custom_components/energidataservice/sensor.py", line 289, in validate_data
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/energidataservice/sensor.py", line 727, in _format_list
    price = self._calculate(
  File "/config/custom_components/energidataservice/sensor.py", line 647, in _calculate
    self._api.tariff_data["tariffs"][str(fake_dt.hour)]
KeyError: '0'


```

## Diganostics data from the device

```text

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.3.5",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.10",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Copenhagen",
    "os_name": "Linux",
    "os_version": "5.15.90",
    "supervisor": "2023.03.1",
    "host_os": "Home Assistant OS 9.5",
    "docker_version": "20.10.22",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "deepstack_face": {
      "version": "0.9.0",
      "requirements": [
        "pillow",
        "deepstack-python==0.8"
      ]
    },
    "bibliotek_dk": {
      "version": "0.3.6",
      "requirements": [
        "beautifulsoup4",
        "html.parser"
      ]
    },
    "spotcast": {
      "version": "v3.6.30",
      "requirements": []
    },
    "sonoff": {
      "version": "3.4.0",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    },
    "novafos": {
      "version": "4.0.0",
      "requirements": []
    },
    "eloverblik": {
      "version": "0.2.0",
      "requirements": [
        "pyeloverblik==0.4.1"
      ]
    },
    "smartthings": {
      "version": "1.0",
      "requirements": [
        "pysmartapp==0.3.3",
        "pysmartthings==0.7.6"
      ]
    },
    "cover_rf_time_based": {
      "version": "1.1.3",
      "requirements": []
    },
    "aula": {
      "version": "0.1.31",
      "requirements": [
        "beautifulsoup4",
        "lxml"
      ]
    },
    "xiaomi_cloud_map_extractor": {
      "version": "v2.2.0",
      "requirements": [
        "pillow",
        "pybase64",
        "python-miio",
        "requests",
        "pycryptodome"
      ]
    },
    "frigate": {
      "version": "4.0.0-beta4",
      "requirements": [
        "pytz==2022.7"
      ]
    },
    "googlewifi": {
      "version": "0.1.34",
      "requirements": [
        "googlewifi==0.0.21"
      ]
    },
    "garbage_collection": {
      "version": "4.10.2",
      "requirements": [
        "python-dateutil>=2.8.2"
      ]
    },
    "philips_android_tv": {
      "version": "1.0.0",
      "requirements": [
        "wakeonlan"
      ]
    },
    "localtuya": {
      "version": "5.0.0",
      "requirements": []
    },
    "eforsyning": {
      "version": "2.0.2",
      "requirements": []
    },
    "dukaone": {
      "version": "1.0.6",
      "requirements": [
        "dukaonesdk==1.0.4"
      ]
    },
    "home_connect_alt": {
      "version": "0.6.1-b3",
      "requirements": [
        "home-connect-async==0.7.7"
      ]
    },
    "hacs": {
      "version": "1.31.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "energidataservice": {
      "version": "1.3.0",
      "requirements": [
        "async-retrying==0.2.2",
        "CurrencyConverter==0.17.5"
      ]
    }
  },
  "integration_manifest": {
    "after_dependencies": [
      "http"
    ],
    "codeowners": [
      "@MTrab"
    ],
    "config_flow": true,
    "documentation": "https://github.com/MTrab/energidataservice/blob/master/README.md",
    "domain": "energidataservice",
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/MTrab/energidataservice/issues",
    "name": "Energi Data Service",
    "requirements": [
      "async-retrying==0.2.2",
      "CurrencyConverter==0.17.5"
    ],
    "version": "1.3.0",
    "is_built_in": false
  },
  "data": {
    "entry": {
      "entry_id": "2fede4cda4386877322e638315cb0051",
      "version": 1,
      "domain": "energidataservice",
      "title": "Energi Data Service2",
      "data": {
        "name": "Energi Data Service2"
      },
      "options": {
        "tariff_charge_owner": "Elinord",
        "enable_forecast": false,
        "enable_tariffs": true,
        "area": "West of the great belt",
        "vat": true,
        "in_cent": false,
        "decimals": 3,
        "pricetype": "kWh",
        "cost_template": "{{0.0|float}}",
        "name": "Energi Data Service2",
        "country": "Denmark"
      },
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": "**REDACTED**",
      "disabled_by": null
    },
    "today": [
      [
        124.0,
        "2023-03-20T00:00:00+01:00"
      ],
      [
        114.940002,
        "2023-03-20T01:00:00+01:00"
      ],
      [
        113.059998,
        "2023-03-20T02:00:00+01:00"
      ],
      [
        110.18,
        "2023-03-20T03:00:00+01:00"
      ],
      [
        104.620003,
        "2023-03-20T04:00:00+01:00"
      ],
      [
        116.400002,
        "2023-03-20T05:00:00+01:00"
      ],
      [
        132.509995,
        "2023-03-20T06:00:00+01:00"
      ],
      [
        148.429993,
        "2023-03-20T07:00:00+01:00"
      ],
      [
        144.940002,
        "2023-03-20T08:00:00+01:00"
      ],
      [
        134.259995,
        "2023-03-20T09:00:00+01:00"
      ],
      [
        117.480003,
        "2023-03-20T10:00:00+01:00"
      ],
      [
        104.389999,
        "2023-03-20T11:00:00+01:00"
      ],
      [
        99.68,
        "2023-03-20T12:00:00+01:00"
      ],
      [
        98.080002,
        "2023-03-20T13:00:00+01:00"
      ],
      [
        98.010002,
        "2023-03-20T14:00:00+01:00"
      ],
      [
        99.639999,
        "2023-03-20T15:00:00+01:00"
      ],
      [
        102.43,
        "2023-03-20T16:00:00+01:00"
      ],
      [
        132.820007,
        "2023-03-20T17:00:00+01:00"
      ],
      [
        150.960007,
        "2023-03-20T18:00:00+01:00"
      ],
      [
        165.470001,
        "2023-03-20T19:00:00+01:00"
      ],
      [
        152.360001,
        "2023-03-20T20:00:00+01:00"
      ],
      [
        135.490005,
        "2023-03-20T21:00:00+01:00"
      ],
      [
        127.5,
        "2023-03-20T22:00:00+01:00"
      ],
      [
        117.040001,
        "2023-03-20T23:00:00+01:00"
      ]
    ],
    "today_calculated": false,
    "api_today": [
      [
        124.0,
        "2023-03-20T00:00:00+01:00"
      ],
      [
        114.940002,
        "2023-03-20T01:00:00+01:00"
      ],
      [
        113.059998,
        "2023-03-20T02:00:00+01:00"
      ],
      [
        110.18,
        "2023-03-20T03:00:00+01:00"
      ],
      [
        104.620003,
        "2023-03-20T04:00:00+01:00"
      ],
      [
        116.400002,
        "2023-03-20T05:00:00+01:00"
      ],
      [
        132.509995,
        "2023-03-20T06:00:00+01:00"
      ],
      [
        148.429993,
        "2023-03-20T07:00:00+01:00"
      ],
      [
        144.940002,
        "2023-03-20T08:00:00+01:00"
      ],
      [
        134.259995,
        "2023-03-20T09:00:00+01:00"
      ],
      [
        117.480003,
        "2023-03-20T10:00:00+01:00"
      ],
      [
        104.389999,
        "2023-03-20T11:00:00+01:00"
      ],
      [
        99.68,
        "2023-03-20T12:00:00+01:00"
      ],
      [
        98.080002,
        "2023-03-20T13:00:00+01:00"
      ],
      [
        98.010002,
        "2023-03-20T14:00:00+01:00"
      ],
      [
        99.639999,
        "2023-03-20T15:00:00+01:00"
      ],
      [
        102.43,
        "2023-03-20T16:00:00+01:00"
      ],
      [
        132.820007,
        "2023-03-20T17:00:00+01:00"
      ],
      [
        150.960007,
        "2023-03-20T18:00:00+01:00"
      ],
      [
        165.470001,
        "2023-03-20T19:00:00+01:00"
      ],
      [
        152.360001,
        "2023-03-20T20:00:00+01:00"
      ],
      [
        135.490005,
        "2023-03-20T21:00:00+01:00"
      ],
      [
        127.5,
        "2023-03-20T22:00:00+01:00"
      ],
      [
        117.040001,
        "2023-03-20T23:00:00+01:00"
      ]
    ],
    "tomorrow": null,
    "tomorrow_calculated": false,
    "api_tomorrow": null,
    "predictions": null,
    "api_predictions": null,
    "tariff_data": {
      "additional_tariffs": {
        "transmissions_nettarif": 0.058,
        "systemtarif": 0.054,
        "elafgift": 0.008
      },
      "tariffs": {}
    },
    "next_update": "13:17:54",
    "data_source": "Energi Data Service",
    "home_assistant_tz": "Europe/Copenhagen",
    "home_assistant_currency": "DKK"
  }
}
```

**Comment by MTrab** [comment]
Fixed in next release

**Comment by MTrab** [comment]
To repeat myself: Fixed in next release
