### ISSUE TITLE
Exception in validate_data when dispatching 'eds_update_a8887634391dff8e57ef04b9c67aa351'

### ISSUE THREAD

**Issue by woopstar** [MTrab/energidataservice#333]
### Describe the issue

Saw the following error in my HA logs yesterday.

### What version of Home Assistant Core has the issue?

core-2023.7.3

### What was the last working version of Home Assistant Core?

core-2023.7.3

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

```
2023-07-31 10:00:39.188 WARNING (SyncWorker_7) [custom_components.energidataservice.sensor] Error adding tariffs for 2023-07-31 00:00:00+02:00, no valid tariffs was found!
2023-07-31 10:00:39.200 ERROR (MainThread) [homeassistant.util.logging] Exception in validate_data when dispatching 'eds_update_a8887634391dff8e57ef04b9c67aa351': ()
Traceback (most recent call last):
  File "/config/custom_components/energidataservice/sensor.py", line 301, in validate_data
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/energidataservice/sensor.py", line 727, in _format_list
    price = self._calculate(
            ^^^^^^^^^^^^^^^^
  File "/config/custom_components/energidataservice/sensor.py", line 654, in _calculate
    tariff_value += float(chargeowner_tariff[str(fake_dt.hour)])
                          ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: '0'

2023-07-31 10:00:48.975 WARNING (SyncWorker_42) [custom_components.energidataservice.sensor] Error adding tariffs for 2023-07-31 00:00:00+02:00, no valid tariffs was found!
2023-07-31 10:00:49.008 ERROR (MainThread) [homeassistant.util.logging] Exception in validate_data when dispatching 'eds_update_a8887634391dff8e57ef04b9c67aa351': ()
Traceback (most recent call last):
  File "/config/custom_components/energidataservice/sensor.py", line 301, in validate_data
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/energidataservice/sensor.py", line 727, in _format_list
    price = self._calculate(
            ^^^^^^^^^^^^^^^^
  File "/config/custom_components/energidataservice/sensor.py", line 654, in _calculate
    tariff_value += float(chargeowner_tariff[str(fake_dt.hour)])
                          ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: '0'

2023-07-31 10:09:45.073 WARNING (SyncWorker_40) [custom_components.energidataservice.sensor] Error adding tariffs for 2023-07-31 00:00:00+02:00, no valid tariffs was found!
2023-07-31 10:09:45.095 ERROR (MainThread) [homeassistant.util.logging] Exception in validate_data when dispatching 'eds_update_a8887634391dff8e57ef04b9c67aa351': ()
Traceback (most recent call last):
  File "/config/custom_components/energidataservice/sensor.py", line 301, in validate_data
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/energidataservice/sensor.py", line 727, in _format_list
    price = self._calculate(
            ^^^^^^^^^^^^^^^^
  File "/config/custom_components/energidataservice/sensor.py", line 654, in _calculate
    tariff_value += float(chargeowner_tariff[str(fake_dt.hour)])
                          ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: '0'

2023-07-31 10:10:53.064 WARNING (SyncWorker_42) [custom_components.energidataservice.sensor] Error adding tariffs for 2023-07-31 00:00:00+02:00, no valid tariffs was found!
2023-07-31 10:10:53.095 ERROR (MainThread) [homeassistant.util.logging] Exception in validate_data when dispatching 'eds_update_a8887634391dff8e57ef04b9c67aa351': ()
Traceback (most recent call last):
  File "/config/custom_components/energidataservice/sensor.py", line 301, in validate_data
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/energidataservice/sensor.py", line 727, in _format_list
    price = self._calculate(
            ^^^^^^^^^^^^^^^^
  File "/config/custom_components/energidataservice/sensor.py", line 654, in _calculate
    tariff_value += float(chargeowner_tariff[str(fake_dt.hour)])
                          ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: '0'
```
[config_entry-energidataservice-a8887634391dff8e57ef04b9c67aa351.json.txt](https://github.com/MTrab/energidataservice/files/12213304/config_entry-energidataservice-a8887634391dff8e57ef04b9c67aa351.json.txt)

**Comment by MTrab** [comment]
You didn't attach diagnostics as requested
