### ISSUE TITLE
Error: Retry attempts exceeded for tariffs request.

### ISSUE THREAD

**Issue by Clausr** [MTrab/energidataservice#378]
### Describe the issue

The last 2 nights at app. 00:12 I've been getting errors where tariffs couldn't be fetched. 

When these can't be fetched, all the tariffs defaults to 0, which is being used to calculate the price in the energy section etc.

This error is the last of a string of 4; but I am unsure whether the first one is related to this issue.
In chronological order these errors are:
Logged at 23:59:59:
```
Exception: HTTPSConnectionPool(host='api.eloverblik.dk', port=443): Max retries exceeded with url: /CustomerApi//api/MeterData/GetTimeSeries/2023-09-24/2023-09-24/Hour (Caused by ResponseError('too many 400 error responses'))
Exception: HTTPSConnectionPool(host='api.eloverblik.dk', port=443): Max retries exceeded with url: /CustomerApi//api/MeterData/GetTimeSeries/2023-09-25/2023-09-25/Hour (Caused by ResponseError('too many 400 error responses'))
Exception: HTTPSConnectionPool(host='api.eloverblik.dk', port=443): Max retries exceeded with url: /CustomerApi//api/MeterData/GetTimeSeries/2023-09-26/2023-09-26/Hour (Caused by ResponseError('too many 400 error responses'))
Exception: HTTPSConnectionPool(host='api.eloverblik.dk', port=443): Max retries exceeded with url: /CustomerApi//api/MeterData/GetTimeSeries/2023-09-27/2023-09-27/Hour (Caused by ResponseError('too many 400 error responses'))
Exception: HTTPSConnectionPool(host='api.eloverblik.dk', port=443): Max retries exceeded with url: /CustomerApi//api/MeterData/GetTimeSeries/2023-09-28/2023-09-28/Hour (Caused by ResponseError('too many 400 error responses'))
```

Logged at 00:12:
```
Error during API request: 500, message='Internal Server Error', url=URL('https://api.energidataservice.dk/dataset/DatahubPricelist?filter=%7B%22chargetypecode%22:+%5B%22151-NT01T%22%5D,%22gln_number%22:+%5B%225790000704842%22%5D%7D&sort=ValidFrom+desc&limit=500')
Error during API request: 400, message='Bad Request', url=URL('https://api.energidataservice.dk/dataset/DatahubPricelist?filter=%7B%22chargetypecode%22:+%5B%22151-NT01T%22%5D,%22gln_number%22:+%5B%225790000704842%22%5D%7D&sort=ValidFrom+desc&limit=500')
```

Logged at 00:12
```
ClientResponseError -> Attempts (5) are over for <function Connector.async_call_api at 0x7ffa93160540>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/async_retrying_ng/__init__.py", line 124, in wrapped
    ret = await ret
          ^^^^^^^^^
  File "/config/custom_components/energidataservice/tariffs/energidataservice/__init__.py", line 188, in async_call_api
    resp.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url=URL('https://api.energidataservice.dk/dataset/DatahubPricelist?filter=%7B%22chargetypecode%22:+%5B%22151-NT01T%22%5D,%22gln_number%22:+%5B%225790000704842%22%5D%7D&sort=ValidFrom+desc&limit=500')
```

Logged at 00:12
`Retry attempts exceeded for tariffs request.`

### What version of Home Assistant Core has the issue?

core-2023.8.4

### What was the last working version of Home Assistant Core?

core-2023.8.4

### What type of installation are you running?

Home Assistant Container

### Diagnostics information

None

**Comment by Clausr** [comment]
I just saw the issue in #374 .

I can however add that the issue goes away if I restart the integration.

**Comment by MTrab** [comment]
Please try installing the latest beta release which incorporates a fix (I hope) for this.

**Comment by Clausr** [comment]
Beta seems to work just fine :)
