### ISSUE TITLE
Upgrading to 0.1.8 breaks the integration

### ISSUE THREAD

**Issue by bjornbak** [MTrab/energidataservice#38]
I am now experiencing:

2022-04-04 06:32:42 INFO (MainThread) [custom_components.energidataservice] 
-------------------------------------------------------------------
Energi Data Service integration

Version: v0.1.8
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/mtrab/energidataservice/issues
-------------------------------------------------------------------

2022-04-04 06:32:42 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.energidataservice
2022-04-04 06:32:42 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up energidataservice platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/energidataservice/sensor.py", line 39, in async_setup_entry
    _setup(hass, config, async_add_devices)
  File "/config/custom_components/energidataservice/sensor.py", line 58, in _setup
    region = RegionHandler(area)
  File "/config/custom_components/energidataservice/utils/regionhandler.py", line 45, in __init__
    self.set_region(region)
  File "/config/custom_components/energidataservice/utils/regionhandler.py", line 56, in set_region
    self.currency = Currency(self._currency)
  File "/config/custom_components/energidataservice/utils/regionhandler.py", line 14, in __init__
    self._name = currency["name"]
TypeError: 'NoneType' object is not subscriptable

**Comment by MTrab** [comment]
From which version did you upgrade?

**Comment by bjornbak** [comment]
0.1.7

**Comment by bjornbak** [comment]
I have tried removing the integration and add it again but doesn't fix anything.

**Comment by MTrab** [comment]
Will take a look on a fresh install. Running it myself on my production HA, without issues.

**Comment by bjornbak** [comment]
I think I got an HACS upgrade too last night.. Could it be related to that?

**Comment by MTrab** [comment]
I did too, so no :)

**Comment by MTrab** [comment]
Hmmm - fresh install and no problems.
Could you go into `Configuration > Settings > General` and confirm that you have a currency selected.
The only thing I can think of, is if that value is not set.

**Comment by bjornbak** [comment]
I have 
![image](https://user-images.githubusercontent.com/79479/161495004-d874b6e4-9ef8-4eb0-9868-76ac7a10aa22.png)

**Comment by bjornbak** [comment]
How can I confirm that it is available to the integration?

**Comment by MTrab** [comment]
Do you have the possibility to get your `/config/.storage/core.config` and show the contents here?
It's okay to anonymize lat, lon and URLs

And perhaps set this in your `configuration.yaml` to enable debug logging for the integration:

```
logger:
  default: warning
  logs:
    custom_components.energidataservice: debug
```

Then you should see some lines similar to these from my tester:

```
2022-04-04 07:27:05 DEBUG (MainThread) [custom_components.energidataservice.sensor] Timezone set in ha Europe/Copenhagen
2022-04-04 07:27:05 DEBUG (MainThread) [custom_components.energidataservice.sensor] Currency set in ha EUR
2022-04-04 07:27:05 DEBUG (MainThread) [custom_components.energidataservice.sensor] Country: Denmark
2022-04-04 07:27:05 DEBUG (MainThread) [custom_components.energidataservice.sensor] Region: DK1
2022-04-04 07:27:05 DEBUG (MainThread) [custom_components.energidataservice.sensor] Region description: West of the great belt
2022-04-04 07:27:05 DEBUG (MainThread) [custom_components.energidataservice.sensor] Region currency DKK
```

**Comment by bjornbak** [comment]
```
{
    "version": 1,
    "minor_version": 1,
    "key": "core.config",
    "data": {
        "latitude": 55.xyz,
        "longitude": 12.abc,
        "elevation": 11,
        "unit_system": "metric",
        "location_name": "Home",
        "time_zone": "Europe/Copenhagen",
        "external_url": "https://something.ui.nabu.casa/",
        "internal_url": "http://home-assistant.local:8123",
        "currency": "DKK"
    }
}

```

**Comment by bjornbak** [comment]
Added the debug and restarted HA but it doesn't seem to get far enough to do those print outs:

```
$ fgrep energidataservice config/home-assistant.log
2022-04-04 09:49:28 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration energidataservice which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-04-04 09:49:33 INFO (MainThread) [homeassistant.bootstrap] Setting up stage 2: {'media_source', 'input_boolean', 'rest_command', 'input_text', 'history', 'sensor', 'device_tracker', 'input_number', 'map', 'tesla_custom', 'default_config', 'logbook', 'google', 'zone', 'my', 'timer', 'ipp', 'input_datetime', 'input_select', 'counter', 'input_button', 'mobile_app', 'ble_monitor', 'tts', 'scene', 'tag', 'hacs', 'template', 'ffmpeg', 'tuya', 'automation', 'system_health', 'group', 'blueprint', 'trace', 'energy', 'speedtestdotnet', 'script', 'cast', 'persistent_notification', 'mqtt', 'sun', 'forecast_solar', 'co2signal', 'energidataservice', 'awox', 'met', 'rfxtrx'}
2022-04-04 09:49:34 INFO (MainThread) [homeassistant.setup] Setting up energidataservice
2022-04-04 09:49:34 INFO (MainThread) [homeassistant.setup] Setup of domain energidataservice took 0.0 seconds
2022-04-04 09:49:34 DEBUG (MainThread) [custom_components.energidataservice] Entry data: {'name': 'Energi Data Service Raw'}
2022-04-04 09:49:34 DEBUG (MainThread) [custom_components.energidataservice] Entry options: {'name': 'Energi Data Service Raw', 'area': 'East of the great belt', 'vat': True, 'decimals': 3, 'pricetype': 'kWh', 'cost_template': '{{0.0|float}}'}
2022-04-04 09:49:34 INFO (MainThread) [custom_components.energidataservice] 
https://github.com/mtrab/energidataservice/issues
2022-04-04 09:49:34 DEBUG (MainThread) [custom_components.energidataservice] Initializing Energi Data Service for area DK2
2022-04-04 09:49:34 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.energidataservice
2022-04-04 09:49:34 DEBUG (MainThread) [custom_components.energidataservice.utils.regionhandler] <custom_components.energidataservice.utils.regionhandler.Currency object at 0x7fa58a19c790>
2022-04-04 09:49:34 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up energidataservice platform for sensor
  File "/config/custom_components/energidataservice/sensor.py", line 39, in async_setup_entry
  File "/config/custom_components/energidataservice/sensor.py", line 58, in _setup
  File "/config/custom_components/energidataservice/utils/regionhandler.py", line 45, in __init__
  File "/config/custom_components/energidataservice/utils/regionhandler.py", line 56, in set_region
  File "/config/custom_components/energidataservice/utils/regionhandler.py", line 14, in __init__

```

**Comment by MTrab** [comment]
Aha! It has something to do with the area. If I make one like yours, selecting East, I get the same issue.
Will see what causes this and push a fix ASAP

**Comment by MTrab** [comment]
Stupid stupid stupid typo :D

Oh well - new version ready shortly

**Comment by bjornbak** [comment]
It is worked now! @MTrab Thank you for you swift reaction/fix!
