### ISSUE TITLE
If `carnot` (forecast) fails, everything fails

### ISSUE THREAD

**Issue by mm98** [MTrab/energidataservice#447]
### Describe the issue

Would it be possible to make the integration work, even though `carnot` is failing (server down)? Right now EDS fails completely, when the forecast is failing. This has happened at 00:45 the last two days. Which results in no electricity prices until EDS is manually reloaded in the morning.

### What version of Home Assistant Core has the issue?

core-2024.2.3

### What was the last working version of Home Assistant Core?

None

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

[ha-error.log](https://github.com/MTrab/energidataservice/files/14401249/ha-error.log)

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:352
Integration: Sensor (documentation, issues)
First occurred: February 25, 2024 at 15:14:10 (2 occurrences)
Last logged: 00:45:07

Error while setting up energidataservice platform for sensor
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1173, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 884, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 898, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 963, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 352, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 533, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 782, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1324, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/energidataservice/sensor.py", line 487, in async_added_to_hass
    await self.validate_data()
  File "/config/custom_components/energidataservice/sensor.py", line 348, in validate_data
    await self._api.update_carnot()
  File "/config/custom_components/energidataservice/api.py", line 197, in update_carnot
    self.predictions = await carnot.async_get_forecast(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/energidataservice/forecasts/carnot/__init__.py", line 69, in async_get_forecast
    resp = await self.client.get(url, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 578, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1187, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host whale-app-dquqw.ondigitalocean.app:443 ssl:default [Try again]
```

**Comment by MTrab** [comment]
This integration doesn't do any refresh at 00:45, do you have any automation to reload EDS?
Please disable this as that might mess up the integration

**Comment by MTrab** [comment]
Perhaps Carnot has no data or is not available for some reason, at that time of day.
Anyway - there will be a fix for this in the next release.

**Comment by mm98** [comment]
Your right @MTrab. I had completely forgot about this automation. I added because of #400, since i was also getting `Unknown` errors at midnight.

**Comment by mm98** [comment]
> Eloverblik?! There is no need to use Eloverblik with this integration.

Nordpool 🤣 dunno why i wrote eloverblik 🙈

**Comment by MTrab** [comment]
Again - something that has nothing to do with this integration
