### ISSUE TITLE
Detected blocking call to open inside the event loop by custom integration 'energidataservice'

### ISSUE THREAD

**Issue by TermeHansen** [MTrab/energidataservice#507]
### Describe the issue

After upgrade to HA 2024.6.0 I get a lot of errors in my log:

`2024-06-05 22:05:52.113 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by custom integration 'energidataservice' at custom_components/energidataservice/connectors/energidataservice/__init__.py, line 44: local_tz = pytz.timezone(tz) (offender: /usr/local/lib/python3.12/site-packages/pytz/__init__.py, line 108: return open(filename, 'rb')), please create a bug report at https://github.com/MTrab/energidataservice/issues
`

### What version of Home Assistant Core has the issue?

2024.6.0

### What was the last working version of Home Assistant Core?

2024.5.5

### What type of installation are you running?

Home Assistant Container

### Diagnostics information

None

### Anything in the logs that might be useful for us?

```txt
homeassistant  | 2024-06-05 22:05:52.111 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by custom integration 'energidataservice' at custom_components/energidataservice/connectors/energidataservice/__init__.py, line 44: local_tz = pytz.timezone(tz) (offender: /usr/local/lib/python3.12/site-packages/pytz/__init__.py, line 108: return open(filename, 'rb')), please create a bug report at https://github.com/MTrab/energidataservice/issues
homeassistant  | Traceback (most recent call last):
homeassistant  |   File "<frozen runpy>", line 198, in _run_module_as_main
homeassistant  |   File "<frozen runpy>", line 88, in _run_code
homeassistant  |   File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
homeassistant  |     sys.exit(main())
homeassistant  |   File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
homeassistant  |     exit_code = runner.run(runtime_conf)
homeassistant  |   File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
homeassistant  |     return loop.run_until_complete(setup_and_run_hass(runtime_config))
homeassistant  |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete
homeassistant  |     self.run_forever()
homeassistant  |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
homeassistant  |     self._run_once()
homeassistant  |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once
homeassistant  |     handle._run()
homeassistant  |   File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
homeassistant  |     self._context.run(self._callback, *self._args)
homeassistant  |   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked
homeassistant  |     await self.async_setup(hass, integration=integration)
homeassistant  |   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
homeassistant  |     result = await component.async_setup_entry(hass, self)
homeassistant  |   File "/config/custom_components/energidataservice/__init__.py", line 54, in async_setup_entry
homeassistant  |     result = await _setup(hass, entry)
homeassistant  |   File "/config/custom_components/energidataservice/__init__.py", line 177, in _setup
homeassistant  |     await refresh_co2_data(0)
homeassistant  |   File "/config/custom_components/energidataservice/__init__.py", line 132, in refresh_co2_data
homeassistant  |     await api.updateco2()
homeassistant  |   File "/config/custom_components/energidataservice/api.py", line 127, in updateco2
homeassistant  |     if api.co2data:
homeassistant  |   File "/config/custom_components/energidataservice/connectors/energidataservice/__init__.py", line 181, in co2data
homeassistant  |     return prepare_co2_data(self._co2_result, date, self._tz)
homeassistant  |   File "/config/custom_components/energidataservice/connectors/energidataservice/__init__.py", line 44, in prepare_co2_data
homeassistant  |     local_tz = pytz.timezone(tz)
```

**Comment by MTrab** [comment]
Please upgrade to the latest version

**Comment by MTrab** [comment]
Sorry, just saw it was another error.

**Comment by TermeHansen** [comment]
yep, I'm on `commit 2cffff71a60e4176ca94acf8699f0952826390fb (HEAD, tag: v1.5.6)`
