### ISSUE TITLE
Fixed price not working after update

### ISSUE THREAD

**Issue by mbuhansen** [MTrab/energidataservice#516]
### Describe the issue

Energi data service 1.5.7
After update HA core to 2024.6.2 energi data service Fixed price is not working.
Variable price is working correctly.

### What version of Home Assistant Core has the issue?

2024.6.2

### What type of installation are you running?

Home Assistant Supervised

### Diagnostics information

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:600
integration: Sensor (documentation, issues)
First occurred: 8:47:28 PM (1 occurrences)
Last logged: 8:47:28 PM

Error adding entity sensor.energi_data_service_fast for domain sensor with platform energidataservice
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 600, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 914, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1354, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/energidataservice/sensor.py", line 605, in async_added_to_hass
    await self.validate_data()
  File "/config/custom_components/energidataservice/sensor.py", line 405, in validate_data
    await self._api.update()
  File "/config/custom_components/energidataservice/api.py", line 170, in update
    if api.today and not self.today:
       ^^^^^^^^^
  File "/config/custom_components/energidataservice/connectors/fixedprice/__init__.py", line 76, in today
    return prepare_data(self.value, date, self.tz)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/energidataservice/connectors/fixedprice/__init__.py", line 24, in prepare_data
    local_tz = pytz.timezone(tz)
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pytz/__init__.py", line 170, in timezone
    if zone.upper() == 'UTC':
       ^^^^^^^^^^
AttributeError: 'zoneinfo.ZoneInfo' object has no attribute 'upper'

**Comment by garret** [comment]
I experience the same.

**Comment by lendf** [comment]
i also experience this
