### ISSUE TITLE
Cannot connect to host api.energidataservice.dk

### ISSUE THREAD

**Issue by kejXero** [MTrab/energidataservice#567]
### Describe the issue

Logger: custom_components.energidataservice.tariffs.energidataservice
Source: custom_components/energidataservice/tariffs/energidataservice/__init__.py:209
integration: Energi Data Service (documentation, issues)
First occurred: 01:42:00 (60 occurrences)
Last logged: 02:11:17

Error during API request: Cannot connect to host api.energidataservice.dk:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')]

### What version of Home Assistant Core has the issue?

2024.8.2

### What was the last working version of Home Assistant Core?

2024.8.2

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

[error_log-5.bin.txt](https://github.com/user-attachments/files/16667135/error_log-5.bin.txt)

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: 02:10:04 (1 occurrences)
Last logged: 02:10:04

Error setting up entry Energi Data Service for energidataservice
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/energidataservice/__init__.py", line 54, in async_setup_entry
    result = await _setup(hass, entry)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/energidataservice/__init__.py", line 88, in _setup
    await api.initialize()
  File "/config/custom_components/energidataservice/api.py", line 100, in initialize
    await self._connectors.load_connectors()
  File "/config/custom_components/energidataservice/connectors/__init__.py", line 31, in load_connectors
    modules = await loop.run_in_executor(None, listdir, f"{dirname(__file__)}")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError
```

### Additional information

After restart I am not able to get the integration to work. I have tried to re initialize with out succes.

**Comment by kejXero** [comment]
Updated the integration  :-)
