### ISSUE TITLE
Update to V1.5.12 returns error in config

### ISSUE THREAD

**Issue by LasseHedeby** [MTrab/energidataservice#584]
### Describe the issue

Failed loading the integration

### What version of Home Assistant Core has the issue?

24.9.1

### What was the last working version of Home Assistant Core?

24.9.1

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

Logger: homeassistant.config_entries
Kilde: config_entries.py:604
Første forekomst: 13.48.54 (1 forekomster)
Senest logget: 13.48.54

Error setting up entry Energi Data Service for energidataservice
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/energidataservice/__init__.py", line 54, in async_setup_entry
    result = await _setup(hass, entry)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/energidataservice/__init__.py", line 185, in _setup
    await api.async_get_tariffs()
  File "/config/custom_components/energidataservice/api.py", line 291, in async_get_tariffs
    if self.api.status != 200:
       ^^^^^^^^
AttributeError: 'APIConnector' object has no attribute 'api'

**Comment by Alssund** [comment]
også samme problem, virker, når jeg går tilbage til 1.5.11

**Comment by topgun0dk** [comment]
Can confirm the same issue.

**Comment by MTrab** [comment]
Release have been removed, please downgrade to 1.5.11
