### ISSUE TITLE
AttributeError: 'APIConnector' object has no attribute 'api'

### ISSUE THREAD

**Issue by kaareseras** [MTrab/energidataservice#590]
### Describe the issue

Integration fails with this error:

AttributeError: 'APIConnector' object has no attribute 'api'

stack trace:

Error setting up entry Energi Data Service for energidataservice
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/energidataservice/__init__.py", line 54, in async_setup_entry
    result = await _setup(hass, entry)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/energidataservice/__init__.py", line 185, in _setup
    await api.async_get_tariffs()
  File "/config/custom_components/energidataservice/api.py", line 291, in async_get_tariffs
    if self.api.status != 200:
       ^^^^^^^^
AttributeError: 'APIConnector' object has no attribute 'api'

I have tried to reinstall the integration, and regenerate Carnot key.

### What version of Home Assistant Core has the issue?

core-2024.9.1

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

[home-assistant_energidataservice_2024-09-12T08-10-46.715Z.log](https://github.com/user-attachments/files/16975731/home-assistant_energidataservice_2024-09-12T08-10-46.715Z.log)

### Anything in the logs that might be useful for us?

```txt
Error setting up entry Energi Data Service for energidataservice
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/energidataservice/__init__.py", line 54, in async_setup_entry
    result = await _setup(hass, entry)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/energidataservice/__init__.py", line 185, in _setup
    await api.async_get_tariffs()
  File "/config/custom_components/energidataservice/api.py", line 291, in async_get_tariffs
    if self.api.status != 200:
       ^^^^^^^^
AttributeError: 'APIConnector' object has no attribute 'api'
```

### Additional information

na

**Comment by mm98** [comment]
1.5.12 has been retracted / removed. Downgrade to 1.5.11.

**Comment by kaareseras** [comment]
Thank you, problem is solved
