### ISSUE TITLE
Fixed price sensor requires reload after reboot of home assistant

### ISSUE THREAD

**Issue by nvanggaard** [MTrab/energidataservice#599]
### Describe the issue

If home assistant is restarted, either from frontend or from docker (docker restart >container<) then does the fixed price sensor fail to load.

Docker logs:
```
homeassistant  | 2024-09-24 19:02:17.600 ERROR (MainThread) [homeassistant.components.sensor] Error adding entity sensor.energi_data_service_fixed_price for domain sensor with platform energidataservice
homeassistant  | Traceback (most recent call last):
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2257, in forgiving_float_filter
homeassistant  |     return float(value)
homeassistant  |            ^^^^^^^^^^^^
homeassistant  | ValueError: could not convert string to float: 'unknown'
homeassistant  |
homeassistant  | During handling of the above exception, another exception occurred:
homeassistant  |
homeassistant  | Traceback (most recent call last):
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 603, in async_render
homeassistant  |     render_result = _render_with_context(self.template, compiled, **kwargs)
homeassistant  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2638, in _render_with_context
homeassistant  |     return template.render(**kwargs)
homeassistant  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 1304, in render
homeassistant  |     self.environment.handle_exception()
homeassistant  |   File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 939, in handle_exception
homeassistant  |     raise rewrite_traceback_stack(source=source)
homeassistant  |   File "<template>", line 1, in top-level template code
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2260, in forgiving_float_filter
homeassistant  |     raise_no_default("float", value)
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1871, in raise_no_default
homeassistant  |     raise ValueError(
homeassistant  | ValueError: Template error: float got invalid input 'unknown' when rendering template '{% if states("sensor.ams_monthuse") | float > 334 %}     {% set reduction = ( el_afgift - 0.008 ) | float(0) %}{% endif %}{{ 0.0 - reduction | default(0) | float(0) }}' but no default was specified
homeassistant  |
homeassistant  | The above exception was the direct cause of the following exception:
homeassistant  |
homeassistant  | Traceback (most recent call last):
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 598, in _async_add_entities
homeassistant  |     await coro
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 912, in _async_add_entity
homeassistant  |     await entity.add_to_platform_finish()
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1365, in add_to_platform_finish
homeassistant  |     await self.async_added_to_hass()
homeassistant  |   File "/config/custom_components/energidataservice/sensor.py", line 606, in async_added_to_hass
homeassistant  |     await self.validate_data()
homeassistant  |   File "/config/custom_components/energidataservice/sensor.py", line 410, in validate_data
homeassistant  |     await self._hass.async_add_executor_job(
homeassistant  |   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
homeassistant  |     result = self.fn(*self.args, **self.kwargs)
homeassistant  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/config/custom_components/energidataservice/sensor.py", line 856, in _format_list
homeassistant  |     price = self._calculate(
homeassistant  |             ^^^^^^^^^^^^^^^^
homeassistant  |   File "/config/custom_components/energidataservice/sensor.py", line 801, in _calculate
homeassistant  |     template_value = self._cost_template.async_render(
homeassistant  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 605, in async_render
homeassistant  |     raise TemplateError(err) from err
homeassistant  | homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unknown' when rendering template '{% if states("sensor.ams_monthuse") | float > 334 %}     {% set reduction = ( el_afgift - 0.008 ) | float(0) %}{% endif %}{{ 0.0 - reduction | default(0) | float(0) }}' but no default was specified
```

My template looks like this:
```
{% if states("sensor.ams_monthuse") | float > 334 %}     
{% set reduction = ( el_afgift - 0.008 ) | float(0) %}{% endif %}
{{ 0.0 - reduction | default(0) | float(0) }} 
```

sensor.ams_monthuse is provided by [amsToMqttBridge](https://github.com/UtilitechAS/amsreader-firmware)

### What version of Home Assistant Core has the issue?

core-2024.8.3

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

[home-assistant_energidataservice_2024-09-24T19-19-21.242Z.log](https://github.com/user-attachments/files/17119777/home-assistant_energidataservice_2024-09-24T19-19-21.242Z.log)

**Comment by MTrab** [comment]
You missed a (0) in your template.
Error occurs because the sensor is loaded after EDS

Fixed **template:**

{% if states("sensor.ams_monthuse") | float(0) > 334 %}     
{% set reduction = ( el_afgift - 0.008 ) | float(0) %}{% endif %}
{{ 0.0 - reduction | default(0) | float(0) }}

**Comment by nvanggaard** [comment]
Thanks! 
FYI: it is missing in your wiki as well :)
