### ISSUE TITLE
The access to the URL to energidataservice.dk with filtering report back 403

### ISSUE THREAD

**Issue by Abildgren** [MTrab/energidataservice#643]
### Describe the issue

The access to the URL to energidataservice.dk with filtering report back 403. 

Accessing without filtering like https://api.energidataservice.dk/dataset/DatahubPricelist still provides the unfiletered list but only with tre-for as charger. I don't see what is wrong with the filtering but the syntax may have been changed. 

### What version of Home Assistant Core has the issue?

core-2024.11.2

### What was the last working version of Home Assistant Core?

core-2024.11.1

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

None

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant.config_entries
Source: config_entries.py:635
First occurred: 10:53:04 (2 occurrences)
Last logged: 11:08:31

Error setting up entry Energi Data Service for energidataservice
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/async_retrying_ng/__init__.py", line 124, in wrapped
    ret = await ret
          ^^^^^^^^^
  File "/config/custom_components/energidataservice/tariffs/energidataservice/__init__.py", line 197, in async_call_api
    resp.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1158, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url='https://api.energidataservice.dk/dataset/DatahubPricelist?filter=%7B%22Note%22:%5B%22Elafgift%22,%22Systemtarif%22,%22Transmissions+nettarif%22%5D%7D&limit=500'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/energidataservice/__init__.py", line 54, in async_setup_entry
    result = await _setup(hass, entry)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/energidataservice/__init__.py", line 193, in _setup
    await api.async_get_tariffs()
  File "/config/custom_components/energidataservice/api.py", line 308, in async_get_tariffs
    self.tariff_data = await tariff.async_get_tariffs()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/energidataservice/tariffs/energidataservice/__init__.py", line 61, in async_get_tariffs
    await self.async_get_system_tariffs()
  File "/config/custom_components/energidataservice/tariffs/energidataservice/__init__.py", line 167, in async_get_system_tariffs
    dataset = await self.async_call_api(query)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/async_retrying_ng/__init__.py", line 203, in wrapped
    ret = await ret
          ^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/async_retrying_ng/__init__.py", line 41, in callback
    await asyncio.sleep(attempt * delay)
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 665, in sleep
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError: Global task timeout
```

**Comment by MTrab** [comment]
See #642 or https://www.facebook.com/groups/209025039666209/posts/hej-der-har-v%C3%A6ret-en-del-opslag-om-eds-energidataservice-for-nylig-jeg-er-lige-o/1694302757805089/?__cft__[0]=AZW0-txa6YOMexZRpnHIF0uYjyfyROyotAH5gzVJQT2b1Kktty6YK6v52xo7OaRUORIdqCItENTFQ1bME-MMiiGvnhX_PNXpOhNoutCHnzJVUTwKsP_TBeoyJmRfMXN3RdHiquY1LwB9Sb2wFqx5aPXd2emPjZhgJ7Vr9g-gR4q3fV7DeiMXlf5oaLVeH0ZxG88&__tn__=%2CO%2CP-R
