### ISSUE TITLE
ingen date efter installering og genstart

### ISSUE THREAD

**Issue by koburg** [MTrab/energidataservice#8]
hej 

integration virker ikke ved mig jeg har installeret og genstartet flere gange også
efter den er tilføjet ved integrations.

![image](https://user-images.githubusercontent.com/3473374/160349123-67421e97-59fb-4ebe-b2d1-32bbf35bedf9.png)

`Logger: homeassistant.components.sensor
Source: custom_components/energidataservice/sensor.py:313 
Integration: Sensor (documentation, issues) 
First occurred: 06.11.54 (4 occurrences) 
Last logged: 07.04.05

Error adding entities for domain sensor with platform energidataservice
Error while setting up energidataservice platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 800, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/energidataservice/sensor.py", line 179, in async_added_to_hass
    await self.validate_data()
  File "/config/custom_components/energidataservice/sensor.py", line 153, in validate_data
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 553, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 593, in _async_write_ha_state
    extra_state_attributes = self.extra_state_attributes
  File "/config/custom_components/energidataservice/sensor.py", line 263, in extra_state_attributes
    "raw_tomorrow": self.raw_tomorrow,
  File "/config/custom_components/energidataservice/sensor.py", line 329, in raw_tomorrow
    return self._add_raw(self._api.tomorrow)
  File "/config/custom_components/energidataservice/sensor.py", line 313, in _add_raw
    for i in data:
TypeError: 'NoneType' object is not iterable
`

**Comment by MTrab** [comment]
Der er lige sendt end ny release ud der fikser dette. Opdater din integration, så skulle problemet være løst.

**Comment by koburg** [comment]
ja tak nu virker det. super fedt det du har lavet.
